site_name: Ultrabug
site_url: https://ultrabug.fr
repo_url: https://github.com/ultrabug/ultrabug.fr
site_description: "Ultrabug - Open Source Author and Contributor. Tech Blog and Talks. FPV Handbook and Builds."

# https://squidfunk.github.io/mkdocs-material/
theme:
  name: material
  favicon: assets/images/favicon.ico
  font: false
  # https://materialdesignicons.com/
  icon:
    logo: material/human-greeting
    logo_tech: material/bash
    logo_fpv: material/quadcopter
  features:
    - navigation.tabs
    - navigation.expand
    - navigation.sections
    - toc.integrate
  custom_dir: theme_overrides
extra_css:
  - assets/stylesheets/extra.css
extra:
  social:
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/ultrabug
      name: ultrabug on Twitter
    - icon: fontawesome/brands/github
      link: https://github.com/ultrabug
      name: ultrabug on Github
    - icon: fontawesome/solid/square-rss
      link: https://ultrabug.fr/feed_rss_created.xml
      name: ultrabug RSS feed
copyright: Copyright &copy; 2011-2022 Alexys Jacob

# https://facelessuser.github.io/pymdown-extensions/
markdown_extensions:
  - attr_list
  - admonition
  - meta
  - toc:
      permalink: true
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.superfences

plugins:
  - awesome-pages:
      strict: false
  - redirects
  - search
  - mkdocs-simple-hooks:
      hooks:
        on_config: "hooks.on_config:deploy_hooks"
  - rss:
      date_from_meta:
        as_creation: "date"
        as_update: false
        datetime_format: "%Y-%m-%d"
      pretty_print: !ENV [PRETTY_RSS, false]
      length: 30
      match_path: "Tech Blog/.*"
  - i18n:
      default_language: en
      default_language_only: !ENV [DEFAULT_LANGUAGE_ONLY, false]
      languages:
        en: '<img style="height: 10px; border: 0px;" alt="en" class="twemoji" src="https://twemoji.maxcdn.com/v/latest/svg/1f1ec-1f1e7.svg" title="english" /> English'
        fr: '<img style="height: 10px; border: 0px;" alt="fr" class="twemoji" src="https://twemoji.maxcdn.com/v/latest/svg/1f1eb-1f1f7.svg" title="français" /> Français'
